version: '3.8'

services:
  okr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: okr-flow-backend
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      
      # Configurações do Supabase (obrigatórias)
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      
      # Configurações de Performance
      - WORKERS_COUNT=${WORKERS_COUNT:-4}
      - TIMEOUT_KEEP_ALIVE=${TIMEOUT_KEEP_ALIVE:-65}
      - TIMEOUT_GRACEFUL_SHUTDOWN=${TIMEOUT_GRACEFUL_SHUTDOWN:-15}
      - ENABLE_GZIP=${ENABLE_GZIP:-true}
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE:-16777216}
      
      # Configurações de Cache
      - CACHE_TTL=${CACHE_TTL:-300}
      - CACHE_MAXSIZE=${CACHE_MAXSIZE:-1000}
      
      # Configurações de Conexão
      - CONNECTION_POOL_SIZE=${CONNECTION_POOL_SIZE:-20}
      - CONNECTION_TIMEOUT=${CONNECTION_TIMEOUT:-30}
      
      # Configurações de JWT
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-2592000}
      - JWT_REFRESH_EXPIRATION_TIME=${JWT_REFRESH_EXPIRATION_TIME:-7776000}
      - SESSION_TIMEOUT=${SESSION_TIMEOUT:-86400}
      - EXTEND_SESSION_ON_ACTIVITY=${EXTEND_SESSION_ON_ACTIVITY:-true}
      
      # URLs do Frontend (importante para CORS)
      - FRONTEND_URL=${FRONTEND_URL:-https://okr.nobug.com.br}
      
      # Configurações de pagamento (opcional)
      - ASAAS_API_KEY=${ASAAS_API_KEY:-}
      - ASAAS_BASE_URL=${ASAAS_BASE_URL:-https://www.asaas.com/api/v3}
      
    env_file:
      - .env
    volumes:
      # Volume para persistir logs
      - ./logs:/app/logs:rw
      # Volume para dados temporários
      - ./tmp:/app/tmp:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - okr-network
    
    # Configurações de recursos
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  okr-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

# Para usar este docker-compose em produção:
# 1. Crie um arquivo .env com as credenciais Supabase
# 2. Configure as variáveis de ambiente necessárias
# 3. Execute: docker-compose up -d
# 4. Para parar: docker-compose down
# 5. Para ver logs: docker-compose logs -f okr-backend
# 6. Para atualizar: docker-compose pull && docker-compose up -d --build 